package com.Lenvill.fluids;

import com.Lenvill.Config;
import com.Lenvill.EmberforgedMain;
import minefantasy.mfr.init.MineFantasyItems;
import minefantasy.mfr.item.ItemMetalComponent;
import minefantasy.mfr.registry.material.CustomMaterial;
import minefantasy.mfr.registry.material.CustomMaterialRegistry;
import minefantasy.mfr.registry.material.types.CustomMaterialType;
import net.minecraft.item.Item;
import net.minecraft.item.crafting.Ingredient;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.oredict.OreIngredient;
import teamroots.embers.config.ConfigMaterial;
import teamroots.embers.config.ConfigMisc;
import teamroots.embers.recipe.ItemMeltingRecipe;
import teamroots.embers.recipe.RecipeRegistry;
import teamroots.embers.register.FluidRegister;

import java.awt.*;
import java.util.*;

public class FluidInit {

    public static ArrayList<MoltenFluid> moltenFluids = new ArrayList<>();
    public static Set<String> meltingExclusions = new HashSet<>();

    public static void preInitFluids(FMLPreInitializationEvent event) {
        EmberforgedMain.LOG.info("Dynamically generating molten fluids for entries in the metal_material registry");
        meltingExclusions.addAll(Arrays.asList(Config.disableMetalMelting));

        initFluids(); //Now done dynamically!
        registerFluids(); //Also now done dynamically!
    }

    //Dynamic Fluid initialization
    private static void initFluids() {
        ArrayList<CustomMaterial> metals = CustomMaterialRegistry.getList(CustomMaterialType.METAL_MATERIAL);
        metals.forEach(metal -> {
            if (!FluidRegistry.isFluidRegistered(metal.getName()) && !meltingExclusions.contains(metal.getName())){
                int[] color = metal.getColourRGB();

                moltenFluids.add(new MoltenFluid(metal.getName(), new Color (color[0], color[1], color[2])));
                if(Config.advancedLogs) {
                    EmberforgedMain.LOG.info("Molten {} has been dynamically registered", metal.getName());
                }
            } else if (meltingExclusions.contains(metal.getName()) && Config.advancedLogs) {
                EmberforgedMain.LOG.info("Skipping molten fluid registration for material: '{}' due to config settings", metal.getName());
            }
        });
        EmberforgedMain.LOG.info("All fluids generated by Emberforged: {}", moltenFluids);
    }

    //Dynamic Fluid Registration
    private static void registerFluids() {

        moltenFluids.forEach(moltenFluid -> {
            FluidRegistry.registerFluid(moltenFluid);
            FluidRegistry.addBucketForFluid(moltenFluid);
        });
    }

    public static void addFluidRecipes() {
        //Melting recipes that rely on Ember's fluids
        meltAdd("iron", FluidRegister.FLUID_MOLTEN_IRON);
        meltAdd("gold", FluidRegister.FLUID_MOLTEN_IRON);
        meltAdd("copper", FluidRegister.FLUID_MOLTEN_COPPER);
        meltAdd("silver", FluidRegister.FLUID_MOLTEN_SILVER);
        meltAdd("tin", FluidRegister.FLUID_MOLTEN_TIN);
        meltAdd("bronze", FluidRegister.FLUID_MOLTEN_BRONZE);

        if(ConfigMaterial.LEAD.mustLoad() && CustomMaterialRegistry.getMaterial("lead") != CustomMaterialRegistry.NONE) {
            meltAdd("lead", FluidRegister.FLUID_MOLTEN_LEAD);
        }
        if(ConfigMaterial.DAWNSTONE.mustLoad() && CustomMaterialRegistry.getMaterial("aluminum") != CustomMaterialRegistry.NONE) {
            meltAdd("dawnstone", FluidRegister.FLUID_MOLTEN_DAWNSTONE);
        }
        if(ConfigMaterial.ALUMINUM.mustLoad() && CustomMaterialRegistry.getMaterial("aluminum") != CustomMaterialRegistry.NONE) {
            meltAdd("aluminum", FluidRegister.FLUID_MOLTEN_NICKEL);
        }
        if(ConfigMaterial.NICKEL.mustLoad() && CustomMaterialRegistry.getMaterial("nickel") != CustomMaterialRegistry.NONE) {
            meltAdd("nickel", FluidRegister.FLUID_MOLTEN_NICKEL);
        }
        if(ConfigMaterial.ELECTRUM.mustLoad() && CustomMaterialRegistry.getMaterial("electrum") != CustomMaterialRegistry.NONE) {
            meltAdd("electrum", FluidRegister.FLUID_MOLTEN_ELECTRUM);
        }

        //Dynamic meltAdding
        moltenFluids.forEach(moltenFluid -> {
            meltAdd(moltenFluid.getName(), moltenFluid);
            meltIngotAdd(moltenFluid.getName(), moltenFluid);
        });

        //A couple of specific recipes

        /*
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromItem(EmberforgedItems.runed_dawnstone_plate),new FluidStack(FluidRegister.FLUID_MOLTEN_DAWNSTONE, (2 * ConfigMisc.ingotFluidAmount))));
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromItem(EmberforgedItems.runed_copper_plate),new FluidStack(FluidRegister.FLUID_MOLTEN_COPPER, (2 * ConfigMisc.ingotFluidAmount))));
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromItem(EmberforgedItems.runed_iron_plate),new FluidStack(FluidRegister.FLUID_MOLTEN_IRON, (2 * ConfigMisc.ingotFluidAmount))));
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromItem(EmberforgedItems.runed_silver_plate),new FluidStack(FluidRegister.FLUID_MOLTEN_SILVER, (2 * ConfigMisc.ingotFluidAmount))));
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromItem(EmberforgedItems.gilded_lead_scales),new FluidStack(FluidRegister.FLUID_MOLTEN_LEAD, ConfigMisc.ingotFluidAmount)));
         */
    }

    private static void meltAdd(String material, Fluid fluid) {
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromStacks(MineFantasyItems.bar(material)),new FluidStack(fluid, ConfigMisc.ingotFluidAmount)));
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromStacks(((ItemMetalComponent) MineFantasyItems.CHAIN_MESH).createComponentItemStack(material, 1)),new FluidStack(fluid, ConfigMisc.ingotFluidAmount)));
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromStacks(((ItemMetalComponent) MineFantasyItems.SCALE_MESH).createComponentItemStack(material, 1)),new FluidStack(fluid, ConfigMisc.ingotFluidAmount)));
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromStacks(((ItemMetalComponent) MineFantasyItems.SPLINT_MESH).createComponentItemStack(material, 1)),new FluidStack(fluid, ConfigMisc.ingotFluidAmount)));
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromStacks(((ItemMetalComponent) MineFantasyItems.METAL_HUNK).createComponentItemStack(material, 1)),new FluidStack(fluid, (ConfigMisc.ingotFluidAmount/4))));
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromStacks(((ItemMetalComponent) MineFantasyItems.PLATE).createComponentItemStack(material, 1)),new FluidStack(fluid, (2 * ConfigMisc.ingotFluidAmount))));
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(OreIngredient.fromStacks(((ItemMetalComponent) MineFantasyItems.PLATE_HUGE).createComponentItemStack(material, 1)),new FluidStack(fluid, (4 * ConfigMisc.ingotFluidAmount))));
    }

    //This has to be done separate to avoid overlap with the melting recipes Embers adds by default
    private static void meltIngotAdd(String material, Fluid fluid) {
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(CustomMaterialRegistry.getMaterial(material).getMaterialIngredient(), new FluidStack(fluid, ConfigMisc.ingotFluidAmount)));
    }

    @Deprecated
    private static void meltAdd(Item item, Fluid fluid) {
        RecipeRegistry.meltingRecipes.add(new ItemMeltingRecipe(Ingredient.fromItem(item),new FluidStack(fluid, ConfigMisc.ingotFluidAmount)));
    }
}
