# Project Settings
    mod_version=3.0.0
    mod_id=Emberforged
    mod_group=com.Lenvill
    name=Emberforged
    jar_name=Emberforged
    description="An addon to MinefantasyReforged"
    update_url=
    url=https://www.curseforge.com/minecraft/mc-mods/emberforged
# Forge Settings
    mc_version=1.12.2
    mc_version_short=1.12
    mappings_version=39
    mappings_channel=stable
    mappings_mc_version=1.12
# Publishing
    github=Lenvill-Jarlsen/Emberforged
    curse_project_id=887714
    curse_relations = codechicken-lib-1-8:requiredDependency,mixin-booter:requiredDependency
    curse_versions=Java 8,Forge,Minecraft 1.12:1.12.2
    hook_content=
# Gradle
    #org.gradle.jvmargs=-Xmx3G
    org.gradle.daemon=false